// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-eXY-KkUnpNgxzjsMkowRBFuv6J-cwXA',
    appId: '1:893101703797:web:2cd19120dce74ba90d6e3c',
    messagingSenderId: '893101703797',
    projectId: 'weeklymealplanner-9b139',
    authDomain: 'weeklymealplanner-9b139.firebaseapp.com',
    storageBucket: 'weeklymealplanner-9b139.firebasestorage.app',
    measurementId: 'G-G0ZV0CXBPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxkS7uJehxAH4Tc24--xMPpAgbhDRzZ_Q',
    appId: '1:893101703797:android:030384fbbe9955af0d6e3c',
    messagingSenderId: '893101703797',
    projectId: 'weeklymealplanner-9b139',
    storageBucket: 'weeklymealplanner-9b139.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTzuPalZ10noEPdLazro0OrIgFjv-ATn0',
    appId: '1:893101703797:ios:3f281a187ea848df0d6e3c',
    messagingSenderId: '893101703797',
    projectId: 'weeklymealplanner-9b139',
    storageBucket: 'weeklymealplanner-9b139.firebasestorage.app',
    iosClientId: '893101703797-r30pfavp8s4hdfq6bleq4t8avmn15lsq.apps.googleusercontent.com',
    iosBundleId: 'com.example.mealPlanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTzuPalZ10noEPdLazro0OrIgFjv-ATn0',
    appId: '1:893101703797:ios:3f281a187ea848df0d6e3c',
    messagingSenderId: '893101703797',
    projectId: 'weeklymealplanner-9b139',
    storageBucket: 'weeklymealplanner-9b139.firebasestorage.app',
    iosClientId: '893101703797-r30pfavp8s4hdfq6bleq4t8avmn15lsq.apps.googleusercontent.com',
    iosBundleId: 'com.example.mealPlanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-eXY-KkUnpNgxzjsMkowRBFuv6J-cwXA',
    appId: '1:893101703797:web:b05e265fa012733e0d6e3c',
    messagingSenderId: '893101703797',
    projectId: 'weeklymealplanner-9b139',
    authDomain: 'weeklymealplanner-9b139.firebaseapp.com',
    storageBucket: 'weeklymealplanner-9b139.firebasestorage.app',
    measurementId: 'G-0ZMFWSWD5R',
  );
}
